### PR TITLE
Added authorization support for query string

### PR DESCRIPTION
**Pull request by evalphobia**
This patch enable to use query string as an alternative to request header for AWS authorization.

http://docs.aws.amazon.com/general/latest/gr/sigv4_signing.html

## reproduce step

make a request with AWS authorization info in query string,

```bash
$ curl -H "Accept: application/json" \
-H "Content-type: application/json" \
-H "X-Amz-Target:DynamoDB_20120810.ListTables" \
-H "X-Amz-Content-Sha256:my-sha256" \
-X POST -d "{}" \
"http://localhost:4567/\
?X-Amz-Algorithm=AWS4-HMAC-SHA256\
&X-Amz-Credential=cred%2F20150101%2Fus-east-1%2Fdynamodb%2Faws4_request\
&X-Amz-Date=20150101T100000Z\
&X-Amz-Expires=300\
&X-Amz-SignedHeaders=host%3Bx-amz-target\
&X-Amz-Signature=my-signature"

{"__type":"com.amazon.coral.service#MissingAuthenticationTokenException","message":"Request is missing Authentication Token"}
```

it shows failed to recognize auth info in query string.

## test steps

prepare this commit,

```bash
$ git remote add pr git@github.com:evalphobia/dynalite.git
$ git fetch pr
$ git checkout -b feature/auth-query-string  pr/feature/auth-query-string
```

and run dynalite server.

Then, make a request with AWS authorization info in query string,

```bash
$ curl -H "Accept: application/json" \
-H "Content-type: application/json" \
-H "X-Amz-Target:DynamoDB_20120810.ListTables" \
-H "X-Amz-Content-Sha256:my-sha256" \
-X POST -d "{}" \
"http://localhost:4567/\
?X-Amz-Algorithm=AWS4-HMAC-SHA256\
&X-Amz-Credential=cred%2F20150101%2Fus-east-1%2Fdynamodb%2Faws4_request\
&X-Amz-Date=20150101T100000Z\
&X-Amz-Expires=300\
&X-Amz-SignedHeaders=host%3Bx-amz-target\
&X-Amz-Signature=my-signature"

{"TableNames":[]}
```

It shows success with `{"TableNames":[]}`.

Next, check the missing paramter request,

```bash
$ curl -H "Accept: application/json" \
-H "Content-type: application/json" \
-H "X-Amz-Target:DynamoDB_20120810.ListTables" \
-H "X-Amz-Content-Sha256:my-sha256" \
-X POST -d "{}" \
"http://localhost:4567/\
?X-Amz-Algorithm=AWS4-HMAC-SHA256\
&X-Amz-Credential=cred%2F20150101%2Fus-east-1%2Fdynamodb%2Faws4_request\
&X-Amz-Date=20150101T100000Z\
&X-Amz-Expires=300\
&X-Amz-SignedHeaders=host%3Bx-amz-target"

{"__type":"com.amazon.coral.service#MissingAuthenticationTokenException","message":"Request is missing Authentication Token"}
```

It shows failed to authorize since the rack of necessary parameter.

----

actually I'm not a nodejs coder, so my code could be violated some common rules.
When that, please tell me  ; )
thanks.

### CODE REVIEW

**Comment by mhart** [comment]
Great! Thanks for doing this – I hadn't realised that DynamoDB could be called this way.

I'm on vacation at the moment, but I should be able to have time in the next few days to look this over.

**Comment by evalphobia** [comment]
@mhart 
How was your vacation? 
It seemed to be conflicted whiled ago, so I just amended my commit and re-pushed it.

If you have anything unsure or a better approach I'd be happy to discuss it ;)

**Comment by mhart** [comment]
Finally got around to testing this – thanks so much!

Merged in, modified slightly, and published as v0.9.0

**Comment by evalphobia** [comment]
Great! thanks!
so I can use dynalite for golang sdk =)

**Comment by mhart** [comment]
Oh right – so the golang sdk uses query string authentication? Seems a bit weird, no? Isn't it more efficient (ie, less bytes) just to use the standard Authorization header?

**Pull request merged**
