### PR TITLE
Adding stream support to Dynalite

### PR DESCRIPTION
**Pull request by mcwhittemore**
@mhart - I need stream support for some tests I'm writing. Is this something you are interested in adding to dynalite? I see its mentioned in the TODOs.

Todos for this PR:

- only allow streams for tables with stream configs
- send old and new items per the stream config
- support batch sizes
- valid event schema (right now it's just the subsections I need)

/cc @rclark @scothis

### CODE REVIEW

**Comment by mhart** [comment]
@mcwhittemore thanks for the PR! I gather you haven't seen #67 😸

**Comment by mcwhittemore** [comment]
Oh man. Sorry. I looked for a PR a few weeks ago. Nice to see this is moving.

**Comment by mhart** [comment]
No worries – now that the holidays are over I should have some time to look at how best to achieve this – so perhaps things can be pulled together from both your work and that of @kiril-pirozenko-home24

**Comment by mcwhittemore** [comment]
@kiril-pirozenko-home24's is much closer to be done it looks like. Though, mine was designed around hooking up triggers and I'm not 100% sure how to do that with what's in #67 right now. I'll close this and make some comments over there.

**Pull request closed without merging**
